FROM ${base_image_name}

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get -y install ffmpeg

RUN pip install flask gunicorn jinja2 psycopg2 mutagen flask-sqlalchemy flask-migrate flask-login

COPY . .

CMD gunicorn streamtagger:app -b 0.0.0.0:5000 --timeout=120 --access-logfile -

EXPOSE 5000
