FROM ${base_image_name}

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get -y install libtag1-dev python3-dev && \
    pip install flask gunicorn jinja2 psycopg2 pytaglib mutagen

COPY . .

CMD gunicorn streamtagger:app -b 0.0.0.0:5000 --access-logfile -

EXPOSE 5000
